services:
  cusdis:
    image: djyde/cusdis:latest
    env_file: .env
    volumes:
      - cusdis_data:/data
    restart: unless-stopped
    mem_limit: 150m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  caddy:
    image: caddy:alpine
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
    mem_limit: 50m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  cusdis_data: